### ISSUE TITLE
percent sign as just p

### ISSUE THREAD

**Issue by jneilliii** [dattas/OctoPrint-DetailedProgress#13]
I recently installed your plugin and I have an issue where the percent complete string is showing the letter p instead of the % sign on the lcd.  What can I do to resolve that?  Using default settings.

**Comment by ProfDrYoMan** [comment]
Have a look here: https://github.com/dattas/OctoPrint-DetailedProgress/pull/10
and here: https://github.com/ProfDrYoMan/OctoPrint-DetailedProgress/blob/c57181131d508569bb9b4823494f0873d01021a4/README.md

Pullrequest is not accepted, because it may fail with some software. For me it works with repetier-dev and marlin 1.1.x.

**Comment by vbz89** [comment]
I am having the same issue. I'm on marlin 1.1.8.

**Comment by brunofporto** [comment]
Same issue. Marlin 1.1.8
