### ISSUE TITLE
Cant find settings file to modify output

### ISSUE THREAD

**Issue by bionno** [dattas/OctoPrint-DetailedProgress#22]

**Comment by bionno** [comment]
Hello,
like in the title, where is the folder/files to modify the OUTPUT ?

Thanks,
A.

**Comment by sfeakes** [comment]
Looks like it goes in the plugin section of octoprint's config.yaml

So copy the settings listed on the main page, (except the _plugins:_) statement, and paste them in Octoprint's config.yaml under the _plugins:_ section. Then modify as you want.

Octoprints's config.yaml is usually in /home/<user_name>/.octoprint/config.yaml

I can't test this as I'm printing at the moment.

**Comment by sfeakes** [comment]
I just tried this.  The config.yaml file is the place for the configuration, but be careful with the settings listed on the main page, as it looks like they are incorrect.

Using the settings I get checksum error when it tried to print.

```
Send: N11 M117 ETL: 01:59:08*118
Recv: Error:No Checksum with line number, Last Line: 10
```

Without them
```
Send: N11 M117 ETL 01h59m08s*58
```

So it looks like my printer control board doesn't like the `:` character, which would make sense since it's a special character in GCODE.
So you'll probably need to play with the `eta_strftime` and `etl_format ` format strings. 

I just had a quick look at the source code.  Looks like these are the lines you should use in the `
plugins: -> detailedprogress:` part of `config.yaml`
```
    eta_strftime: "%H %M %S Day %d"
    etl_format: "{hours:02d}h{minutes:02d}m{seconds:02d}s"
```

and **_NOT_**

```
    eta_strftime: "%H:%M:%S Day %d"
    etl_format: "{hours:02d}:{minutes:02d}:{seconds:02d}"
```

Another potential error is the % in complete since that's also a special character in gcode.  so you may also ned to change
```
- "{completion:.2f}% complete"
-- TO --
- "{completion:.2f}p complete"
```
